# Generated by Django 5.2.6 on 2025-10-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardsmodel',
            old_name='member_count',
            new_name='members',
        ),
    ]
