# Generated by Django 5.2.6 on 2025-10-24 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0003_board_ticket_delete_boardsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='boards_app.board'),
        ),
    ]
