# Generated by Django 5.2.6 on 2025-10-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0004_alter_ticket_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='tasks_high_prio_count',
        ),
        migrations.RemoveField(
            model_name='board',
            name='tasks_to_do_count',
        ),
        migrations.RemoveField(
            model_name='board',
            name='ticket_count',
        ),
    ]
