# Generated by Django 5.2.6 on 2025-10-24 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0006_alter_board_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='boards_app.board'),
        ),
    ]
